### ISSUE TITLE
Error checking for inclusion of non-existent properties does not work

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc-rebind#13]
If you try to include a property that doesn't exist, the error check here previously threw an error:

https://github.com/d3fc/d3fc-rebind/blob/master/src/rebindAll.js#L9

However, `rebindAll` currently iterates over source properties, and as a result incorrect inclusions are not highlighted.

**Comment by chrisprice** [comment]
I don't think this is possible to fix for `rebindAll` as it is fundamentally about building a pipeline of transformations with no termination hook (i.e. no point at which a pipeline step could signal an error). However, b5c70136c7a9d3c015cd31789d02c181109e4d58 fixes this for `rebind`.
