### ISSUE TITLE
Module name query

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc-rebind#3]
Just wondering why the module name is `fc_rebind`:

https://github.com/d3fc/d3fc-rebind/blob/master/rollup.config.js#L5

I'd have thought `fc.rebind` or just `fc` makes more sense?

**Comment by chrisprice** [comment]
We copied the d3 style e.g. `d3-layout` is `d3_layout`. I suppose anything with a `.` in it would now be considered a legacy namespacing technique and just `fc` could conflict with another `d3fc-*` package.
